language: php
php:
  - 5.4
  - 5.5
  - 5.6
branches:
  only:
    - develop
    - master
before_script:
  - composer self-update
  - composer -n --no-ansi install --prefer-source
script:
  - ./vendor/bin/phpunit --verbose -c tests/phpunit.xml.travis
